image: atlassian/default-image:2

definitions:
  create-upload-and-deploy-docker-image: &create-upload-and-deploy-docker-image
    name: "Create, upload and deploy docker image"
    image: atlassian/default-image:2
    services:
      - docker
    script:
      - docker build -t ${PROJECT_NAME}-${CONTAINER_NAME}-${ENV_NAME}:latest -f ./Dockerfile .
      - pipe: atlassian/aws-ecr-push-image:1.4.2
        variables:
          IMAGE_NAME: ${PROJECT_NAME}-${CONTAINER_NAME}-${ENV_NAME}
      - pipe: atlassian/aws-ecs-deploy:1.6.0
        variables:
          CLUSTER_NAME: ${PROJECT_NAME}-${ENV_NAME}
          SERVICE_NAME: ${PROJECT_NAME}-${CONTAINER_NAME}-${ENV_NAME}
          FORCE_NEW_DEPLOYMENT: 'true'

pipelines:
  branches:
    develop:
      - step:
          <<: *create-upload-and-deploy-docker-image
          deployment: develop
    staging:
      - step:
          <<: *create-upload-and-deploy-docker-image
          deployment: staging

